[colors.cursor]
cursor = "0xa51b6d"
#cursor = "0xff4151"

[colors.normal]
black = "0x4C566A"
blue = "0x81A1C1"
cyan = "0x88C0D0"
green = "0xA3BE8C"
magenta = "0xB48EAD"
red = "0xBF616A"
white = "0xE5E9F0"
yellow = "0xEBCB8B"

[colors.primary]
#background = "0x0f111a"
#foreground = "0xD8DEE9"

background = "0x0e0014"
foreground = "0xCAA9E0"
[font]
size = 14

[font.bold]
family = "UbuntuMono Nerd Font"

[font.italic]
family = "UbuntuMono Nerd Font"

[font.normal]
family = "UbuntuMono Nerd Font"
style = "Regular"

[window]
opacity = 0.9

[window.padding]
x = 2
